### ISSUE TITLE
Expose RExpress as a module

### ISSUE THREAD

**Issue by theplatypus** [See-d-SAS/RExpress#4]
## Synopsis

Be able to require RExpress as a module, and thus dynamically add middlewares.

### Run in standalone 

```bash
npm start 8080

# main.js
# const rexpress = require('rexpress')
# rexpess.listen(8080)
````

### Run as a module

```javascript
const rexpress = require('rexpress')

// rexpress is a wrapper of the express app()
rexpress.get('/path/to/route', (req, res) => {
    res.send(200)
} )

rexpess.listen(8080)
```

## Implementation

In `api.js`, wrap the express `app` object into the rexpress namespace.

**Comment by See-d-Team** [comment]
Create a middleware to automate the routes.
Initialize the name of the R function in the main.js and execute the route's function in api.js by using next().

As the application is composed of several middlewares, they are executed in a stric order : 
 - Cors
 - parse_body
 - custom_routes (in this example)
and then execute the function.
